### ISSUE TITLE
XSplitVcam Background Removal

### ISSUE THREAD

**Issue by gereky** [tharmes42/WebcamOnDesktop#18]
Thank yo Tobias for this usefull product.
I have been using vCamDesk for a while. It has background removal functionality.
However when I tried to use WebCamOnDesktop, the background reflects black.
Do you have any advice?
Kind regards

**Comment by tharmes42** [comment]
This is a limitation by the Windows App Container. vCamDesk uses deep (and soon to be deprecated) Win32-functionalities. WebCamOnDesktop is an official windows app - but has more limitations. One of them: no way to have full transparency to the desktop. :( I hope Microsoft will provide a way to have that for apps too someday.
