### ISSUE TITLE
Bigger Camera

### ISSUE THREAD

**Issue by nemix** [tharmes42/WebcamOnDesktop#19]
Hello, can you please update it so we can make the camera as big as we want, its a bit too small for me personally.

**Comment by tharmes42** [comment]
Unfortunately, using the offical picture-in-picture API function in windows limits the maximum size of the window. However, you can adjust the zoom level on your desktop, this also enlarges the maximum allowed picture-in-picture size. (I hope Microsoft changes that someday).
