### ISSUE TITLE
Masking of camera

### ISSUE THREAD

**Issue by kennethaar** [tharmes42/WebcamOnDesktop#20]
Would it be possible to mask the window so you could change the shape and border of the picture? Like a circle or or some such.

See this video to see the possibilities.

https://www.youtube.com/watch?v=PgZDfp7qMO4

PS: I love this app. Thank you for making it.

**Comment by tharmes42** [comment]
Thanks for your input. I would love to have that, too. Currently the windows API does not allow to use any other shape than rectangle. And it does not allow transparency down to the underlying app or desktop. So even if there would be a circle shape - it still would be surrounded by a non-transparent rectangle.
