### ISSUE TITLE
Can you make available the executable?

### ISSUE THREAD

**Issue by Danielhextronics** [tharmes42/WebcamOnDesktop#25]
I only find download link for the source which I have no idea how to open on windows. I want to use the software. Where can I download the WebcamOnDesktop.exe  ?

**Comment by tharmes42** [comment]
Done, I added a [WebcamOnDesktop_1.0.10.0_x64.msixbundle](https://github.com/tharmes42/WebcamOnDesktop/releases/download/v.1.0.10.0/WebcamOnDesktop_1.0.10.0_x64.msixbundle) to the [releases](https://github.com/tharmes42/WebcamOnDesktop/releases).
