### ISSUE TITLE
Can't install from MSIX

### ISSUE THREAD

**Issue by ZodmanPerth** [tharmes42/WebcamOnDesktop#26]
I tried installing version 1.0.10.0 from the MSIX bundle, but the certificate failed:

![image](https://github.com/user-attachments/assets/6a358fd1-41d6-409c-bb2b-77ddb8c4a9f7)

I've tried installing the certificate to a few of my local stores but nothing seems to work.

Can you provide some install instructions in the readme on Github about installing from the MSIX bundle please?

**Comment by ZodmanPerth** [comment]
Ah, I figured it out.

```
Right click the msix bundle
Properties
Select Digital Signatures Tab
Click on the signature in the table
Click Details
View Certificate
Install Certificate
Local Machine
Next (Hit yes for the UAC prompt that comes up)
Select Place All Certificates in the following store
Browse
Select Trusted People
Next
Finish
Then close out of everything
```

**Comment by Engoni** [comment]
> Ah, I figured it out.
> 
> ```
> Right click the msix bundle
> Properties
> Select Digital Signatures Tab
> Click on the signature in the table
> Click Details
> View Certificate
> Install Certificate
> Local Machine
> Next (Hit yes for the UAC prompt that comes up)
> Select Place All Certificates in the following store
> Browse
> Select Trusted People
> Next
> Finish
> Then close out of everything
> ```

Thanks man, that worked, your a lifesaver! lets hope Microsoft allows the app again, it has many uses!

**Comment by ZodmanPerth** [comment]
Agreed.  Your app does what no other app on Windows does.  I'm astounded Microsoft won't let you have it in the store.
