### ISSUE TITLE
mirror video

### ISSUE THREAD

**Issue by amin007** [tharmes42/WebcamOnDesktop#7]
can you make mirror video or flip left right up down?

**Comment by seekinsp** [comment]
X 2 for this feature please!

**Comment by jason3fc** [comment]
Same here! Went looking for this option immediately. Love the app though. its just what I needed.

**Comment by tharmes42** [comment]
Feature now available with https://github.com/tharmes42/WebcamOnDesktop/releases/tag/v1.0.7.0
:)
